### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by 11jo**
Hello, here is a french translation for Northern Tales of the Sword Coast by [Streen](https://www.baldursgateworld.fr/memberlist.php?mode=viewprofile&u=7598) from la Couronne de Cuivre.

### CODE REVIEW

**Comment by Roberciiik** [comment]
Hi @11jo ! Could you please update the README file with the authors of the translation? Thank you!

**Comment by 11jo** [comment]
Yes I can, but I don't know where to add it, sorry...

[I don't see any mention of others translators](https://github.com/SpellholdStudios/NTotSC/blob/7ed76c696128a127d2730767bdf38e4943bcd044/ntotsc/docs/readme-ntotsc.txt#L242), can you point me to the right direction ?

**Comment by Roberciiik** [comment]
Right, let me add a new section for it. I will back to you. 👀

**Comment by Roberciiik** [comment]
@11jo 
Hello, I've added an extra section in the README file for translation recognition. Could you please update this section, as well as the changes version history. 
Thank you.

**Comment by 11jo** [comment]
Hum, it seem that my pull request has conflict now. Do you prefer me to close and redo the pull request or the readme conflict can be forced ?

I have added your last version of the readme it's probably where I did wrong.

**Comment by Roberciiik** [comment]
The best option is to merge or rebase your local changes to the latest origin master. I did the merge for you.

**Comment by 11jo** [comment]
Thanks Roberciiik !

Good evenning to you.

**Pull request merged**
