### PR TITLE
Added missing weights to the items from the todo list.

### PR DESCRIPTION
**Pull request by Roberciiik**

### CODE REVIEW

**Comment by Gitjas** [comment]
As far as I know, the weight data is an EE specific feature on the item description, at least for items like rings etc. I would like the descriptions for the classic engine (in setup.tra) to remain consistent with the original game.

**Comment by Roberciiik** [comment]
Sure! I just followed a note in "todo" list. I will update this as you requested.

**Comment by Roberciiik** [comment]
Done. Kept weight of belt in setup.tra.

**Comment by Gitjas** [comment]
What todo list are you referring to?

**Comment by Roberciiik** [comment]
```
-known issues
Could probably be fixed by someone else:
-- EET: some of the symbols are very near to SoD symbols on the worldmap
--wenn man von der Karte mit dem Tempel der Schwarzen Hand direkt nach Larswood (Turm) geht, dann landet au�erhalb der Karte und steckt somit fest (ohne Teleportieren).
--Some scripts seem off. some orc priests and mages only attacked me with melee weapons, they didn't cast spells. 
-     Setup.tra errors: Will ring, ring of resistance, girdle of stromos, potions - weight not mentioned
    Will armor and evalt blade dont have Str requirements
-Will's voiceset: some lines seem in wrong order ```
from ntotsc.tp2

**Comment by Gitjas** [comment]
Apologies then, as this seems to be either a leftover or a misunderstanding. Thanks for the edits.

**Pull request merged**
