### PR TITLE
Added sirine's isle to the Worldmap. Updated dedicated icon of Northern Citadel.

### PR DESCRIPTION
**Pull request by Roberciiik**

### CODE REVIEW

**Comment by Roberciiik** [comment]
Changing to draft as BP-BGT-Worldmap is still in progress with implementation of new icons.

**Comment by GraionDilach** [comment]
You're also forgetting EET and it's own areas.tbl.

**Comment by Roberciiik** [comment]
EET has already correct icon set for Northern Citadel, and there is no free island on map for Sirinie's isle to be placed for EET. This icon is natively supported in EET. So the change is strictly related to BP-BGT-Worldmap.

**Comment by GraionDilach** [comment]
I mean you're not updating https://github.com/SpellholdStudios/NTotSC/blob/master/ntotsc/worldmap/eet/areas.tbl.

Also, I'm not sure what's the issue with the free island. We can add additional islands as fake "map icons" on top of the map itself. CtB does that via dropping Hlondeth to the bottom-left corner. https://github.com/SpellholdStudios/Check_the_Bodies/blob/master/CtB/Worldmap/eet/eet-areas.tbl#L5

**Comment by Roberciiik** [comment]
Sure, I can add sirine's island to the EET worldmap too, as you described.

**Comment by GraionDilach** [comment]
Reviewing the BP-BGT iconset, I would suggest the already existing icon 82 for the Sirene Island to be placed somewhere. I presume this icon is in the mods for the Werewolf Island but not used.

**Comment by Roberciiik** [comment]
I've added sirine's island also to EET worldmap, with icon 82, as you suggested.

**Comment by Roberciiik** [comment]
Changing to "Ready for review" as BP-BGT-Worldmap v11 provides all required icons.

**Pull request merged**
