### PR TITLE
Tactical components install fix and other bug fixes

### PR DESCRIPTION
**Pull request by AngelGryph**

### CODE REVIEW

**Comment by Gitjas** [comment]
Thanks very much!
The fall back to English translation strings would need an update after the utf8 conversion for the EEs, too I think.

**Comment by Gitjas** [comment]
JFI I changed it locally to
 		LOAD_TRA ~ntotsc/language/english/journal.tra~
		LOAD_TRA ~ntotsc/language/%LANGUAGE%/journal.tra~
		LOAD_TRA ~ntotsc/language/english/setup-ee.tra~
		LOAD_TRA ~ntotsc/language/%LANGUAGE%/setup-ee.tra~

-this also fixes a potential crash bug for journal entries for non-English games. o.O

**Comment by Gitjas** [comment]
I'll never learn that text in tildas leads to them exed out when posting here. m(

**Comment by Gitjas** [comment]
> JFI I changed it locally to LOAD_TRA ~ntotsc/language/english/journal.tra~ LOAD_TRA ~ntotsc/language/%LANGUAGE%/journal.tra~ LOAD_TRA ~ntotsc/language/english/setup-ee.tra~ LOAD_TRA ~ntotsc/language/%LANGUAGE%/setup-ee.tra~
> 
> -this also fixes a potential crash bug for journal entries for non-English games. o.O

Dang, no, that doesn't work because the English lines aren't in utf8. Removing...

**Comment by GwendolyneFreddy** [comment]
Try this \~hskhjfks\~   (backslash before each tilde). :wink:

**Comment by Gitjas** [comment]
Thanks! /~test/~

**Comment by Gitjas** [comment]
Haha! \~test2\~

**Comment by Gitjas** [comment]
Ha!

**Comment by GwendolyneFreddy** [comment]
MARDOWN is a very weird language, like WeiDU.... It took me a long time to understand how to display text between tildes in readme file...

**Comment by Gitjas** [comment]
I didn't even know that name!
Thanks again. I hope i remember next time I post tra lines.

**Comment by Roberciiik** [comment]
You can also use a "code snippet" by using backticks: `~test~`

**Pull request merged**
